### ISSUE TITLE
用了我的代码，只字不提，还在代码里面写上自己的地址

### ISSUE THREAD

**Issue by kn007** [veryer/wordpress#1]
只字不提，还在代码里面写上自己的地址，署了自己的名

https://kn007.net/topics/cdn-share-my-hook-function/

**Comment by veryer** [comment]
您好，因为代码用的早，在网上搜的，后来没有找到作者，就分享了，非常抱歉，我已经增加了作者，如果有其他要求还请告知，我会在收到消息第一时间更改

**Comment by kn007** [comment]
感谢。
不好意思，最近心情不好，有点愤青了。
语气不善之处，还望见谅。

**Comment by veryer** [comment]
我已经在网站发帖公示，并打算置顶7天，以表歉意，感谢您不计我的过失

**Comment by kn007** [comment]
额，客气了，置顶就不用了。感谢对我的认可。
